language: rust

os:
  - linux
  - osx
  - windows

rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build
  - cargo test

notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always
